# Databricks Apps Configuration

command: ["uvicorn", "app:app", "--host", "0.0.0.0"]

env:
  - name: DATABRICKS_HOST
    value: "https://e2-demo-west.cloud.databricks.com"
  - name: DEBUG
    value: "false"
